Description: >
    Project 4 / Udacity 2020

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        
Resources:
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0  
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt install -y default-jdk 
          wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
          sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt-get update -y
          sudo apt-get install -y jenkins
          sudo systemctl start jenkins
          sudo systemctl enable jenkins
      KeyName: pipeline            
      ImageId: ami-0d1cd67c26f5fca19
      SecurityGroupIds:
      - Ref: WebServerSecGroup
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      InstanceType: t2.micro
      
Outputs:    
  WebInstance: 
      Description: public URL on EC2 for accessing the webpage
      Value: !Join ['',['http://', !GetAtt WebInstance.PublicDnsName,':8080']]
      Export:
        Name: !Sub ${EnvironmentName}-DNS-Name
